export const MODULE = {
  PLANOS_TREINO:      'planos-de-treino',
  BANCO_EXERCICIOS:   'banco-de-exercicios',
  TREINOS_EXTRAS:     'treinos-extras',
  EXECUCAO_TREINO:    'execucao-do-treino',
  TREINO_ADAPTATIVO:  'treino-adaptativo',
  FREQUENCIA:         'frequencia',
  AVALIACOES:         'avaliacoes-fisicas',
  ANAMNESE:           'anamnese',
  FEEDBACKS:          'feedbacks',
  FATURAS:            'faturas',
  ARQUIVOS:           'arquivos',
  MEU_PROGRESSO:      'meu-progresso',
  WHITE_LABEL:        'white-label',
  NOTIFICACOES:       'notificacoes',
  MINHA_AGENDA:       'minha-agenda',
  PLANOS_ALIMENTARES: 'planos-alimentares',
  GAMIFICACAO:        'gamificacao-ranking',
  ASSISTENTE_IA:      'assistente-ia',
  DESAFIOS:           'desafios',
  RELATORIO_EVOLUCAO: 'relatorio-de-evolucao',
  RADAR_RETENCAO:     'radar-de-retencao',
  BIBLIOTECA_CONTEUDO: 'biblioteca_conteudo',
} as const;

export type ModuleSlug = typeof MODULE[keyof typeof MODULE];
